import type { Metadata } from 'next'
import Header from '@/components/document-layout/header'
import Footer from '@/components/document-layout/footer'

export const metadata: Metadata = {
    title: 'NexaDash',
    description: 'Generated by AppStoneLab',
}

export default async function documentLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <div className="flex min-h-screen flex-col bg-gray-200 font-gilroy text-base/5 font-medium text-black antialiased">
            <Header />
            <div className="grow">{children}</div>
            <Footer />
        </div>
    )
}
